env:
  contexts:
    - name: "default"
      urls:
        - "http://juice-shop:3000"

jobs:
  - type: spider
    parameters:
      context: "default"

 
  - type: report
    parameters:
      template: traditional-html
      reportDir: "/zap/output"
      reportFile: "zap-report.html"
      reportTitle: "ZAP Baseline Report"
