name: DevSecOps Pipeline

on:
  push:
  pull_request:

env:
  IMAGE_NAME: ghcr.io/gag-007/lurj_project/juice-shop
  DOCKER_TAG: ${{ github.sha }}

jobs:

  # ------------------------------
  # Stage 1: SAST (Semgrep)
  # ------------------------------
  sast:
    name: SAST (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        continue-on-error: true
        with:
          config: auto
          generateSarif: true
          output: semgrep.sarif
      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif

  # ------------------------------
  # Stage 2: Dependency Scan (Trivy)
  # ------------------------------
  dependency_scanning:
    name: Dependency Scan (Trivy)
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          TRIVY_VERSION="0.45.0"
          for i in {1..5}; do
            wget https://github.com/aquasecurity/trivy/releases/download/v$TRIVY_VERSION/trivy_${TRIVY_VERSION}_Linux-64bit.deb && break
            echo "Повторная попытка через 10 секунд..."
            sleep 10
          done
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb
      - name: Run Trivy FS scan
        run: trivy fs --scanners vuln --format json --output trivy-report.json .
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json

  # ------------------------------
  # Stage 3: Docker Build & Push
  # ------------------------------
  docker_build:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: dependency_scanning
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$DOCKER_TAG .
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$DOCKER_TAG

    # ------------------------------
  # Stage 4: DAST (OWASP ZAP)
  # ------------------------------
  dast:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v4

      - name: Run Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop $IMAGE_NAME:$DOCKER_TAG
          echo "Waiting for Juice Shop to be ready..."
          sleep 20

      - name: Fix permissions for ZAP workspace
        run: |
         docker run --rm --entrypoint "" \
          -v ${{ github.workspace }}:/zap/wrk \
          zaproxy/zap-stable:latest \
          sh -c "chown -R 1000:1000 /zap/wrk"

      - name: Run ZAP Baseline Scan
        run: |
         docker run --rm  \
          -v ${{ github.workspace }}:/zap/wrk \
          --network="juice-shop_default" \
          -v $(pwd):/zap/wrk/:rw \
          zaproxy/zap-stable:latest \
          zap.sh -cmd -autorun /zap/wrk/zap.yaml
            
      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
         name: zap-reports
         path: |
           zap-report.html
           zap-report.json






